name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn && npm install -g firebase-tools
      - name: Build
        run: yarn run build
      - name: Deploy
        run: firebase deploy --token FIREBASE_LOGIN_CI_TOKEN
        env:
          FIREBASE_LOGIN_CI_TOKEN: ${{ secrets.FIREBASE_LOGIN_CI_TOKEN }}
