name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: sudo chown -R $USER /usr/local && yarn
      - name: Test
        run: yarn run test --watchAll=false
